---
name: sevilla-imd-website

services:
### Plone CMS #########################################
  backend:
    build:
      context: ./backend
      args:
        - PLONE_VERSION=${PLONE_VERSION:-6.1.2}
    environment:
      RELSTORAGE_DSN: "dbname='${DB_NAME:-plone}' user='${DB_NAME:-plone}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-jtSdjwghqspy}' port='${DB_PORT:-5432}'"
    ports:
      - "${PLONE_PORT}:8080"
    depends_on:
      - db

### PostgreSQL Server #########################################
  db:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_SYSTEM_DEFAULT_TEXT_SEARCH_CONFIG: ${POSTGRES_DEFAULT_TEXT_SEARCH_CONFIG}
      TZ: ${POSTGRES_TZ}
      PGTZ: ${POSTGRES_PGTZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - vol-site-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

### Docker Volumes #########################################
volumes:
  vol-site-data: {}
