---
name: sevilla-imd-website

services:
### Plone CMS #########################################
  backend:
    build:
      context: ./backend
      args:
        - PLONE_VERSION=${PLONE_VERSION:-6.1.2}
    environment:
      RELSTORAGE_DSN: "dbname='${DB_NAME:-plone}' user='${DB_NAME:-plone}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-jtSdjwghqspy}' port='${DB_PORT:-5432}'"
    ports:
      - "${PLONE_PORT}:8080"
    depends_on:
      - db

### PostgreSQL #########################################
  db:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - vol-site-data:/var/lib/postgresql/data

volumes:
  vol-site-data: {}
