blank_issues_enabled: false
contact_links:
  - name: Consulta general
    url: https://github.com/notacool/default-repository/discussions
    about: Si tienes dudas generales, usa el apartado de Discussions.
