from plone.dexterity.content import DexterityContent
from sevilla.imd.website import _
from zope.interface import provider
from zope.schema.interfaces import IVocabularyFactory
from zope.schema.vocabulary import SimpleTerm
from zope.schema.vocabulary import SimpleVocabulary


ACTIVITY = [
    u"Aerostep",
    u"Abdominales",
    u"Apnea",
    u"Aquagym",
    u"Aquamantenimiento",
    u"Aquapilates",
    u"Artes Marciales",
    u"Baile Moderno Kids",
    u"Baloncesto",
    u"Balonmano",
    u"Balonmano Playa",
    u"Béisbol",
    u"Bolos montañeses",
    u"Cardio Combat",
    u"Cardiobox",
    u"Ciclo Indoor",
    u"Circuito Grupal",
    u"Circuito Perdida Peso",
    u"Core Fitness",
    u"Cursos de natación",
    u"Danza Oriental",
    u"Dragon Boat",
    u"Ejercicios acuáticos para la salud",
    u"Energy Power",
    u"Entrenamiento funcional",
    u"Escuela para la salud",
    u"Estiramientos",
    u"Fitness",
    u"Fitness Balance",
    u"Fútbol",
    u"Fútbol 7",
    u"Fútbol Americano",
    u"Fútbol playa",
    u"Fútbol sala",
    u"GAP",
    u"Gimnasia de Mantenimiento",
    u"Gimnasia de Mantenimiento Jóvenes / Adultos",
    u"Gimnasia de Mantenimiento Senior y 3ª Edad",
    u"Gimnasia Rítmica-Deportiva",
    u"Gimnasio Adultos",
    u"Hidroterapia",
    u"HIIT - Circuito Alta Intensidad",
    u"Karate Infantil",
    u"Kumba",
    u"Lacrosse",
    u"Mini básquet",
    u"Minitenis",
    u"Movilidad",
    u"Musculación",
    u"Natación",
    u"Natación embarazadas",
    u"Natación funcional",
    u"Natación funcional terapéutica",
    u"Natación funcional terapéutica espalda",
    u"Natación libre",
    u"Natación para 'Peques'",
    u"Natación para acompañantes",
    u"Natación para adultos",
    u"Natación para bebés",
    u"Natación para discapacitados",
    u"Natación para jóvenes y mayores",
    u"Natación para mayores de 65",
    u"Natación para peques",
    u"Natación Primaria y Secundaria",
    u"Pádel",
    u"Paddel Surf",
    u"Patinaje Artístico",
    u"Petanca",
    u"Pilates",
    u"Piragüismo",
    u"Power Pump",
    u"Programa Combinado",
    u"Pump",
    u"Regata",
    u"Rugby",
    u"Sofball",
    u"Streching",
    u"Tai-Chi",
    u"Tenis",
    u"Tenis de Mesa",
    u"Tonificación",
    u"Tonificación y Estiramientos",
    u"Voleibol",
    u"Vóley playa",
    u"Yoga",
    u"Zumbón",
    u"Zumbón Familiar",
    u"Zumbón Kids",
]


SPORTS_SPACE = [
    u"Bolera montañesa",
    u"Campo de béisbol de césped artificial",
    u"Campo de fútbol 7",
    u"Campo de fútbol 7 de albero",
    u"Campo de fútbol de albero",
    u"Campo de fútbol de césped artificial",
    u"Campo de petanca",
    u"Campo de regatas",
    u"Campo de rugby",
    u"Circuito de automodelismo",
    u"Circuito exterior",
    u"Equipamiento para tenis de mesa",
    u"Gimnasio",
    u"Pabellón polideportivo cubierto",
    u"Pantalán para embarcaciones",
    u"Piscina",
    u"Piscina cubierta",
    u"Pista automodelismo",
    u"Pista polideportiva",
    u"Pista de arena",
    u"Pista de Atletismo",
    u"Pista de atletismo de tierra",
    u"Pista de bádminton",
    u"Pista de baloncesto",
    u"Pista de balonmano",
    u"Pista de frontenis",
    u"Pista de fútbol sala",
    u"Pista de hockey patines",
    u"Pista de minitenis",
    u"Pista de pádel",
    u"Pista de Running",
    u"Pista de skate y monopatines",
    u"Pista de squash",
    u"Pista de tenis",
    u"Pista de voleibol",
    u"Pista de voley-playa",
    u"Pista polideportiva de césped artificial",
    u"Pista polideportiva exterior cubierta",
    u"Rocódromo",
    u"Sala de aeróbic",
    u"Sala de artes marciales",
    u"Sala de boxeo",
    u"Sala de musculación",
    u"Sala fitness",
    u"Sala Multiusos",
    u"Sala polivalente",
    u"Zona Spa",
]


COMPLEMENTARY_SERVICES = [
    u"Área Social",
    u"Almacén",
    u"Ambigú",
    u"Aseos",
    u"Aseos Públicos",
    u"Ascensor / Elevador",
    u"Aulas de formación",
    u"Botiquín",
    u"Cafetería",
    u"Casa de botes",
    u"Centro de belleza",
    u"Cerramiento exterior",
    u"Circuito de automodelismo",
    u"Enfermería",
    u"Grada",
    u"Iluminación nocturna",
    u"Oficinas",
    u"Oficina de administración",
    u"Parking",
    u"Pozo de riego",
    u"Recepción",
    u"Restaurante",
    u"Sala de entretenimiento",
    u"Sala de reuniones",
    u"Solarium",
    u"Taquillas",
    u"Vestíbulo",
    u"Vestuarios",
    u"Zona ajardinada",
    u"Zona Spa",
]


@provider(IVocabularyFactory)
def management_models(context: DexterityContent):
    """Available Management models for a Sports Center."""
    terms = []
    terms.append(SimpleTerm(value="direct", token="direct", title=_("Direct")))
    terms.append(SimpleTerm(value="indirect", token="indirect", title=_("Indirect")))
    return SimpleVocabulary(terms)
